blank_issues_enabled: true
contact_links:
    about: Ask questions and discuss with other community members.
  - name: Write Us an E-Mail
    url: mailto:contact@sophiaiii.com
    about: Sponsorship, Media, and other topics not related to troublshooting, bug reports or feature requests.
